# 认证配置文件
users:
  - username: admin
    api_key: admin_api_key_123
    permissions:
      - submit
      - manage
      - monitor
  - username: user
    api_key: user_api_key_456
    permissions:
      - submit
      - monitor

