# Base configuration file
base:
  # 用户数，协程池数
  # 默认值: 100
  users: 100

  # 任务默认循环次数
  # 默认值: 1
  # 设置多个可重复执行，设置为非正整数无效
  task_default_repeats: 1

  # 任务间隔，单位为毫秒
  # 默认值: 1000
  task_interval: 1

  # 定时执行时长，单位为秒
  # 默认值: 0
  # 非正数代表不走定时执行逻辑；设置为正整数则走定时执行逻辑
  scheduled_duration: 0

  # 测试数据格式
  # 默认值: none, 不生成本地测试数据
  # 可选值: none, jtl
  # 当值为jtl时，将会将测试结果文件以jtl数据格式保存在本地
  test_data_format: jtll

  # HTML测试报告
  # 默认值: false
  # 可选值: true, false
  # 若值为true，执行完任务后会生成html格式任务执行报告
  html_test_report: true

  # AI分析
  # 默认值: false
  # 可选值: true, false
  # 启用AI分析时会将进行智能分析测试结果数据，作为后续行程测试结果报告的依据
  ai_analysis: false

  # 知识库链接
  # 默认值: none
  # 不将本次的测试结果数据存储到知识库中
  knowledge_base_link: none

  # Web界面
  # 默认值: false
  # 可选值: true, false
  # 若值为true则启动web界面
  web_interface: false