llm:
  api_type: "openai"  # 可选值：openai / azure / ollama / groq 等
  base_url: "YOUR_BASE_URL"  # LLM API 的基础 URL，通常是类似于 https://api.openai.com/v1
  api_key: "YOUR_API_KEY"  # 您的 API 密钥
  model: "gpt-4-turbo"  # 可选：gpt-4-turbo / gpt-3.5-turbo 等，取决于使用的模型
  proxy: "YOUR_PROXY"  # 可选：代理设置，用于 LLM API 请求
  # timeout: 600 # 可选：API 请求的超时时间，单位：秒。如果设置为 0，将使用默认值 300
  # pricing_plan: "" # 可选：对于 Azure LLM，当模型名称与 OpenAI 不同且需要设置计费计划时使用
  pricing_plan: ""  # 可选：Azure LLM 的定价计划名称，若与 OpenAI 使用相同的模型名，可留空
  access_key: "YOUR_ACCESS_KEY"  # 可选：访问密钥，仅适用于某些提供商（如自托管或云服务）
  secret_key: "YOUR_SECRET_KEY"  # 可选：访问密钥，仅适用于某些提供商（如自托管或云服务）
  session_token: "YOUR_SESSION_TOKEN"  # 可选：会话令牌，仅适用于某些云服务
  endpoint: "YOUR_ENDPOINT"  # 可选：自托管模型时使用的端点地址
  # region_name: "us-west-1"  # 可选：对于 AWS 或 Azure 的区域设置